---
# https://eslint.org/docs/user-guide/configuring#specifying-environments

extends:
  - "airbnb-base"
  - "eslint:recommended"

env:
  node: true
  es2020: true

parserOptions:
  ecmaVersion: latest

rules:
  no-console: 0
  indent: ["error", 2]
  max-len: ["error", { "code": 100 }]
  import/extensions: # FIXME: remove when rule will be adjusted for new nodejs version
    - error
    - ignorePackages
    - js: always
