---
# https://eslint.org/docs/user-guide/configuring#specifying-environments

plugins:
    - fp

extends:
    - "airbnb-base"
    - "plugin:fp/recommended"

env:
    node: true
    es2020: true

parserOptions:
    ecmaVersion: latest

rules:
    no-console: 0
    indent: ["error", 4]
    max-len: ["error", { "code": 160 }]
    import/extensions: # FIXME: remove when rule will be adjusted for new nodejs version
        - error
        - ignorePackages
        - js: always
    no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
    fp/no-loops: 0
    fp/no-nil: 0
    fp/no-unused-expression: 0
    fp/no-let: 0
    fp/no-throw: 0
    fp/no-mutation: 0
    fp/no-mutating-methods: 0
